### ISSUE TITLE
[h-encore / henkaku / no enso] Getting "This Device Not Supported" when mounting UMA as ux0

### ISSUE THREAD

**Issue by Duckyz** [CelesteBlue-dev/PSVita-StorageMgr#16]
Running H-Encore on 3.68, when trying to mount UMA as ux0 on my PSTV it reboots and says that the device isn't supported. I am able to manually mount the USB as ux0 via VitaShell so I doubt the USB is the problem. [Log](https://pastebin.com/NcTRVUMh)

**Comment by CelesteBlue-dev** [comment]
from somebody : 
"I got a h-encore pstv on 3.68 i moved on 3.65 enso so i could games that require 3.68 i need some help my h-encore crashes and says file is corrupted and also my usb is not mounting as my memory card like other people what am i doing thats so different?"

**Comment by richard1222** [comment]
I fixed my issue it seems i can link you the article to get your problem fixed if you like?

**Comment by CelesteBlue-dev** [comment]
@richard1222 I think I fixed your issue in today commits, but yes please show me the link.a

**Comment by CelesteBlue-dev** [comment]
@richard1222 I don't know if I helped you but today I fixed issue #16 in which you are commenting.
with commit https://github.com/CelesteBlue-dev/PSVita-StorageMgr/commit/e1892a3842256fabafaa948168fdd3599b9f0505
Your issue was to never have mounted USB as ux0 using VitaShell before using StorageMgr.
