### ISSUE TITLE
2TB HDD on PSTV (3.65 Enso) Free Space/Used Space Incorrect

### ISSUE THREAD

**Issue by IcySon55** [CelesteBlue-dev/PSVita-StorageMgr#74]
PSTV 3.65 Enso
StorageMgr 3.0
2TB WD Blue, exFAT 128K Clusters (Smallest cluster size allowed by the Windows formatting tool)

Actually used space: 57GB

Settings App:
Displays the incorrect amount of free space as roughly: 999GB

VitaShell:
Displays the incorrect amount of used space as roughly: 984GB

In all cases the capacity is correct at : 1.82TB

**Comment by CelesteBlue-dev** [comment]
Hello. Maybe it's because cluster size is too big. Please, if you have no important data on your HDD, use a formatting tool to format with lower clusters. Formatting will remove all data from HDD so backup your data before formatting. If you don't find such a tool for your OS, use gparted or linux to do it. Thanks.

**Comment by IcySon55** [comment]
It appears that using the command line in Windows 7,8,10, it is possible to create the partition correctly.

`format E: /A:64K /FS:exFAT /Q`

I am now copying back all of my files and will be testing later tonight.

**Comment by IcySon55** [comment]
I can confirm that forcing 64K clusters during formatting via the command line has created a fully working 2TB partition with free/used space calculations being correct!

I've seen this issue in several places/threads on reddit and can now actually solve them.

**Comment by CelesteBlue-dev** [comment]
Thank you very much ! I have updated the README.
